"""init

Revision ID: 78463f3ccf25
Revises: 
Create Date: 2023-12-12 09:19:20.747352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "78463f3ccf25"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "items",
        sa.Column("item_num", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("items_pkey")),
        sa.UniqueConstraint("item_num", name=op.f("items_item_num_key")),
    )
    op.create_index(op.f("items_id_idx"), "items", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("items_id_idx"), table_name="items")
    op.drop_table("items")
    # ### end Alembic commands ###
